/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.
    
    Handles any on screen GUI controls or visualisations
  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "../../aquila-build/aquila-src/aquila/global.h"
#include "../../aquila-build/aquila-src/aquila/source/generator/SineGenerator.h"
#include "../../aquila-build/aquila-src/aquila/tools/TextPlot.h"

//==============================================================================
/**
*/
class _3daudioVstAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    //_3daudioVstAudioProcessorEditor(); //default constructor, just bc
    _3daudioVstAudioProcessorEditor (_3daudioVstAudioProcessor&);
    ~_3daudioVstAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    _3daudioVstAudioProcessor& processor;
    
    //Slider object for volume control
    
    Slider midiVolume;
    Slider freq;
    Slider phase;
    Slider time;
    Slider filter;
    
    //Aquila Stuff
    //Aquila::SineGenerator sine;
    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (_3daudioVstAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
